swagger: "2.0"
info:
  description: "API de Perfiles de Usuarios"
  version: "1.0.0"
  title: "Perfiles de Usuarios API"
host: "localhost:5500"
basePath: "/"
schemes:
  - "http"
paths:
  /profile:
    get:
      summary: "Obtener todos los perfiles"
      operationId: "getProfiles"
      responses:
        200:
          description: "Lista de perfiles"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Profile"
    post:
      summary: "Crear un nuevo perfil"
      operationId: "createProfile"
      parameters:
        - name: "body"
          in: "body"
          description: "Datos del perfil a crear"
          required: true
          schema:
            $ref: "#/definitions/Profile"
      responses:
        201:
          description: "Perfil creado exitosamente"
          schema:
            $ref: "#/definitions/Profile"
  /profile/{id}:
    get:
      summary: "Obtener un perfil por ID"
      operationId: "getProfileById"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del perfil a obtener"
          required: true
          type: "integer"
      responses:
        200:
          description: "Perfil encontrado"
          schema:
            $ref: "#/definitions/Profile"
        404:
          description: "Perfil no encontrado"
    put:
      summary: "Actualizar un perfil existente"
      operationId: "updateProfile"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del perfil a actualizar"
          required: true
          type: "integer"
        - name: "body"
          in: "body"
          description: "Datos del perfil actualizado"
          required: true
          schema:
            $ref: "#/definitions/Profile"
      responses:
        200:
          description: "Perfil actualizado exitosamente"
          schema:
            $ref: "#/definitions/Profile"
        404:
          description: "Perfil no encontrado"
    delete:
      summary: "Eliminar un perfil"
      operationId: "deleteProfile"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del perfil a eliminar"
          required: true
          type: "integer"
      responses:
        200:
          description: "Perfil eliminado exitosamente"
        404:
          description: "Perfil no encontrado"
definitions:
  Profile:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      last_name:
        type: "string"
      age:
        type: "integer"
        format: "int32"
